version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    #working_directory: ~/goof # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run: 
          name: install packages (npm install)
          command: 'npm install'
      - run:
          name: install-snyk 
          command: 'sudo npm install -g snyk'   
      - run:
          name: install snyk-to-html
          command: 'sudo npm install snyk-to-html -g'   
      - run: # run snyk auth - authenticate snyk use environment variables to add token
          name: snyk auth
          command: snyk auth $API_TOKEN
     
      - run: # run snyk test - run snyk test
          name: snyk code test
          command: snyk code test --json | snyk-to-html -o SAST_results.html || true

      - run: # run snyk test - run snyk test
          name: snyk SCA test
          command: snyk test --json | snyk-to-html -o SCA_results.html
      
      - store_artifacts:
          path: SCA_results.html
          destination: SCA_results.html
      - store_artifacts:
          path: SAST_results.html
          destination: SAST_results.html

#     - run:
#          name: snyk monitor
#          command: snyk monitor 

